name: indigitech_shop
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  webview_flutter: ^4.9.0
  google_fonts: ^6.2.1
  gap: ^3.0.1
  material_symbols_icons: ^4.2762.0
  flutter_staggered_grid_view: ^0.7.0
  carousel_slider: ^5.0.0
  ensure_visible_when_focused: ^1.2.0
  dropdown_button2: ^2.3.9
  #flutter_recaptcha_v2_compat: ^1.0.5
  flutter_inappwebview: ^6.0.0
  http: ^1.2.2
  shared_preferences: ^2.0.0
  fluttertoast: ^8.1.1
  url_launcher: ^6.3.1
  intl: ^0.17.0
  geolocator: ^13.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.9

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/images/
    - assets/images/Categories/Handicrafts/BARMM/Higaonon/Pottery/
    - assets/images/Categories/Handicrafts/BARMM/Higaonon/Basketry/
    - assets/images/Categories/Handicrafts/BARMM/Lambangian/Basketry/
    - assets/images/Categories/Handicrafts/BARMM/Lambangian/Pottery/
    - assets/recaptcha.html